Error handling, download info

diff --git a/bin/music_download b/bin/music_download
--- a/bin/music_download
+++ b/bin/music_download
@@ -5,8 +5,20 @@ if [[ ! -f $HOME/.music_to_download ]]; then
     exit 0
 fi
 
+tmp_file=$(mktemp)
+
 cd $HOME/Music/Downloads
 for url in $(cat $HOME/.music_to_download); do
-    youtube-dl --extract-audio --audio-format mp3 --audio-quality 0 $url
+    echo -n "Downloading $(youtube-dl --no-warnings --get-title $url 2>/dev/null)..."
+    youtube-dl --extract-audio --audio-format mp3 --audio-quality 0 $url >/dev/null 2>&1
+
+    if [[ $? -eq 0 ]]; then
+        echo 'Done'
+    else
+        echo 'Error'
+        echo $url >> $tmp_file
+    fi
 done
+
+mv $tmp_file $HOME/.music_to_download
 
